# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      cargo:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "⬆️ cargo:"
    cooldown:
      default-days: 14

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "⬆️ gha:"
    cooldown:
      default-days: 14
